### ISSUE TITLE
Customize 404 Page

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#34]
On the 404 page, make the 404 much smaller and put help text that describes how the search works. The search is nice but the extra search characters are not obvious to everyone. 

https://lunrjs.com/guides/searching.html#fields

Only describe search elements (like *) that are relevant; I don't know if we have fields.

**Comment by RohitChattopadhyay** [comment]
![image](https://user-images.githubusercontent.com/19877300/59857662-fec1c500-9396-11e9-8c02-6173f7229a79.png)

@cannin , requesting feedback

Previous 404 image was taken from Google Images, thus I have changed it. I have made the current one.
Our search supports only wildcard as advanced search because  `+ - :` has special meaning in our database thus they are escaped,
