### ISSUE TITLE
Test Out Import Script on Full Dataset 

### ISSUE THREAD

**Issue by cannin** [cannin/ihop-reach#6]
Test and debug the import script on the full dataset; link to data sent separately.

**Comment by RohitChattopadhyay** [comment]
**Full data-set took 18.5 hours** for importing. Document count is around 3.5million
**Import was successful and was completed without any error.**
Import rate was around **10,000 documents per 30 minutes**.
I am **unable to share** the dumped Mongodb files(2.3GB) **due to its size**. Suggest me how can I share it with you(@cannin ).

**Comment by cannin** [comment]
Closing for now.
